ARG NODE_VERSION=16
ARG SERVER_PORT=3000

FROM node:$NODE_VERSION-alpine

WORKDIR /app

COPY package.json yarn.lock

RUN yarn yarn install --frozen-lockfile && yarn cache clean

COPY . .

RUN yarn lerna bootstrap && yarn cache clean
RUN yarn build:client

EXPOSE $SERVER_PORT

CMD [ "yarn serve --scope=client", './']